#!/bin/bash -ilex

if test -d ${name}
then
pushd ${name}

git fetch --all -p

    if git reset --hard && git checkout ${branchName} && git pull origin ${branchName}
        then
            popd
        else
            echo -e "!!pulling error===>git:${name}, branch:${branchName}"
            popd
            exit 1
        fi
    else
        git clone ${git_address} ${name} --branch ${branchName}

        if [ ! -d ${name} ]; then
            echo -e "!!clone error===>git:${name}, branch:${branchName}"
            exit 1
        fi
    fi
    
    pushd ${name}
    npm install --registry=https://registry.npm.taobao.org
    npm run build
    
popd

node /root/yueyue/buildAjx/src/bin/uploadH5.js --output=${WORKSPACE}/${name}/${output} --tenantId=${tenantId} --destPath=${destDir} --env=${env}